-- =====================================================
-- SHOPIFY EXTENSION PRODUCTS (50 Additional Products)
-- Premium products from the Shopify Admin Extension
-- =====================================================

INSERT INTO products (handle, title, description, vendor, product_type, tags, price, compare_at_price, image_url, status, margin_percent, inventory_quantity) VALUES
-- Smart Home & Electronics
('wifi-smart-led-light-bulbs-4pack', 'WiFi Smart LED Light Bulbs - Voice Control & App Enabled (4-Pack)', 'Transform your home with intelligent lighting. These WiFi-enabled LED bulbs offer seamless voice control compatibility and smartphone app integration, allowing you to adjust brightness, color temperature, and schedules from anywhere.', 'Express Prime', 'Smart Home', ARRAY['smart-tech', 'trending', 'bestseller', 'ai-pick'], 39.95, 69.99, 'https://images.unsplash.com/photo-1565814329452-e1efa11c5b89?w=800', 'active', 42.9, 200),
('3in1-wireless-charging-station', '3-in-1 Wireless Charging Station - Fast Charge for iPhone, AirPods & Apple Watch', 'Eliminate cable clutter with this premium all-in-one charging solution. Simultaneously power your iPhone, AirPods, and Apple Watch with advanced fast-charging technology.', 'Express Prime', 'Electronics', ARRAY['smart-tech', 'bestseller', 'new', 'ai-pick'], 49.95, 89.99, 'https://images.unsplash.com/photo-1586953208270-767889fa9a0b?w=800', 'active', 44.5, 150),
('usb-portable-blender-smoothie', 'USB Rechargeable Portable Blender - Personal Size Smoothie Maker', 'Blend healthy smoothies anywhere with this powerful cordless blender. Features a robust motor and stainless steel blades that effortlessly crush ice and frozen fruit.', 'Express Prime', 'Kitchen Gadgets', ARRAY['trending', 'bestseller', 'ai-pick'], 34.95, 59.99, 'https://images.unsplash.com/photo-1570222094714-4e3c3c5c5d0b?w=800', 'active', 41.7, 180),
('smart-fingerprint-door-lock', 'Smart Fingerprint Door Lock - Keyless Entry with App Control & Auto-Lock', 'Upgrade your home security with cutting-edge biometric technology. Store up to 100 fingerprints for family and trusted guests.', 'Express Prime', 'Smart Home', ARRAY['smart-tech', 'new', 'ai-pick'], 129.95, 199.99, 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800', 'active', 35.0, 60),
('hepa-air-purifier-uvc', 'HEPA Air Purifier with UV-C Light - Smart Auto Mode for Large Rooms', 'Breathe cleaner, healthier air with this advanced purification system. True HEPA filter captures 99.97% of airborne particles.', 'Express Prime', 'Smart Home', ARRAY['smart-tech', 'bestseller', 'ai-pick'], 89.95, 149.99, 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800', 'active', 40.0, 75),

-- Health & Wellness
('cordless-neck-shoulder-massager', 'Cordless Neck and Shoulder Massager - Deep Tissue Shiatsu with Heat', 'Relieve tension and muscle soreness with professional-grade massage therapy at home. Eight rotating nodes deliver deep-tissue shiatsu massage.', 'Express Prime', 'Health & Wellness', ARRAY['trending', 'bestseller', 'ai-pick'], 59.95, 99.99, 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800', 'active', 40.1, 90),
('wifi-security-camera-2pack', 'WiFi Security Camera 2-Pack - 2K HD Indoor/Outdoor Night Vision', 'Monitor your property with crystal-clear 2K resolution and advanced night vision up to 30 feet.', 'Express Prime', 'Smart Home', ARRAY['smart-tech', 'trending', 'bestseller'], 79.95, 139.99, 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800', 'active', 42.9, 85),
('sonic-electric-toothbrush-8heads', 'Sonic Electric Toothbrush with 8 Brush Heads - USB Rechargeable', 'Achieve dentist-level cleaning at home with 40,000 vibrations per minute. Five brushing modes target different oral care needs.', 'Express Prime', 'Health & Wellness', ARRAY['trending', 'bestseller', 'ai-pick'], 44.95, 79.99, 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800', 'active', 43.8, 140),
('robot-vacuum-mopping', 'Robot Vacuum Cleaner with Mopping - Self-Charging Smart Navigation', 'Experience effortless floor cleaning with intelligent navigation technology. Simultaneously vacuums and mops hard floors.', 'Express Prime', 'Smart Home', ARRAY['smart-tech', 'trending', 'bestseller', 'ai-pick'], 179.95, 299.99, 'https://images.unsplash.com/photo-1558317374-067fb5f30001?w=800', 'active', 40.0, 45),
('adjustable-laptop-stand-aluminum', 'Adjustable Laptop Stand - Ergonomic Aluminum Riser for Desk', 'Improve posture and reduce neck strain with this premium aluminum laptop stand.', 'Express Prime', 'Office Accessories', ARRAY['trending', 'bestseller', 'ai-pick'], 29.95, 49.99, 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800', 'active', 40.1, 130),

-- More Health & Wellness
('heated-eye-mask-usb', 'Heated Eye Mask for Dry Eyes - USB Rechargeable with Timer', 'Soothe tired, dry eyes with therapeutic heat therapy. Adjustable temperature settings provide customized comfort.', 'Express Prime', 'Health & Wellness', ARRAY['trending', 'new', 'ai-pick'], 39.95, 69.99, 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800', 'active', 42.9, 100),
('uv-phone-sanitizer-charger', 'UV Phone Sanitizer & Wireless Charger - Kills 99.9% Bacteria', 'Eliminate harmful germs while charging your phone. Dual UV-C lights sanitize your device in just 10 minutes.', 'Express Prime', 'Electronics', ARRAY['smart-tech', 'trending', 'ai-pick'], 49.95, 79.99, 'https://images.unsplash.com/photo-1586953208270-767889fa9a0b?w=800', 'active', 37.6, 110),
('adjustable-posture-corrector', 'Adjustable Posture Corrector - Back Brace Support for Men & Women', 'Retrain your muscles and improve posture with gentle, effective support.', 'Express Prime', 'Health & Wellness', ARRAY['trending', 'bestseller', 'ai-pick'], 24.95, 44.99, 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800', 'active', 44.6, 180),
('dual-dash-cam-1080p', 'Dual Dash Cam Front and Rear - 1080P HD Night Vision', 'Protect yourself on the road with comprehensive dual-camera coverage.', 'Express Prime', 'Electronics', ARRAY['smart-tech', 'trending', 'bestseller'], 89.95, 149.99, 'https://images.unsplash.com/photo-1609592806596-4e8d2de1c62b?w=800', 'active', 40.0, 65),
('resistance-bands-set-5', 'Resistance Bands Set of 5 - Exercise Bands with Handles', 'Build strength and flexibility with this versatile workout system. Five color-coded resistance levels.', 'Express Prime', 'Fitness', ARRAY['trending', 'bestseller', 'ai-pick'], 29.95, 59.99, 'https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=800', 'active', 50.1, 200),

-- Fitness & Recovery
('vibrating-foam-roller-electric', 'Vibrating Foam Roller - Electric Massage Roller for Recovery', 'Accelerate muscle recovery with powerful vibration therapy. Four intensity levels and textured surface.', 'Express Prime', 'Fitness', ARRAY['trending', 'new', 'ai-pick'], 69.95, 119.99, 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800', 'active', 41.7, 70),
('smart-water-bottle-32oz', 'Smart Water Bottle with Time Marker - Motivational 32oz BPA-Free', 'Stay hydrated throughout the day with visual time markers that track your water intake.', 'Express Prime', 'Fitness', ARRAY['trending', 'bestseller', 'ai-pick'], 19.95, 34.99, 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800', 'active', 43.0, 220),
('wireless-earbuds-bt53-anc', 'Wireless Earbuds Bluetooth 5.3 - Noise Cancelling 40H Playtime', 'Immerse yourself in premium sound quality with advanced Bluetooth 5.3 technology.', 'Express Prime', 'Electronics', ARRAY['smart-tech', 'trending', 'bestseller', 'ai-pick'], 39.95, 79.99, 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800', 'active', 50.1, 160),
('bamboo-desk-organizer-charger', 'Bamboo Desk Organizer with Wireless Charger - Multi-Device Station', 'Declutter your workspace with this elegant all-in-one solution. Sustainable bamboo construction.', 'Express Prime', 'Office Accessories', ARRAY['smart-tech', 'trending', 'ai-pick'], 54.95, 89.99, 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800', 'active', 38.9, 85),
('smart-led-strip-50ft-rgb', 'Smart LED Strip Lights 50ft - WiFi RGB Color Changing Music Sync', 'Create stunning lighting effects with app-controlled RGB LED strips.', 'Express Prime', 'Smart Home', ARRAY['smart-tech', 'trending', 'bestseller', 'ai-pick'], 34.95, 69.99, 'https://images.unsplash.com/photo-1565814329452-e1efa11c5b89?w=800', 'active', 50.1, 175),

-- More Products
('massage-gun-30speeds', 'Massage Gun Deep Tissue - Percussion Massager 30 Speeds', 'Experience professional-grade muscle therapy at home. 30 speed settings and 6 interchangeable heads.', 'Express Prime', 'Health & Wellness', ARRAY['trending', 'bestseller', 'ai-pick'], 89.95, 159.99, 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800', 'active', 43.8, 80),
('magnetic-car-phone-mount', 'Magnetic Car Phone Mount - Dashboard & Windshield Holder', 'Keep your phone secure and accessible while driving. Strong magnetic grip.', 'Express Prime', 'Auto Accessories', ARRAY['trending', 'bestseller', 'ai-pick'], 19.95, 34.99, 'https://images.unsplash.com/photo-1609592806596-4e8d2de1c62b?w=800', 'active', 43.0, 200),
('high-pressure-shower-head', 'High Pressure Shower Head with Handheld - 8 Spray Settings', 'Transform your daily shower into a spa experience. Eight spray patterns.', 'Express Prime', 'Home Improvement', ARRAY['trending', 'bestseller', 'ai-pick'], 39.95, 79.99, 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800', 'active', 50.1, 120),
('portable-air-compressor-tire', 'Portable Air Compressor Tire Inflator - Cordless Digital Gauge', 'Never worry about flat tires again with this compact, powerful inflator.', 'Express Prime', 'Auto Accessories', ARRAY['trending', 'bestseller', 'ai-pick'], 49.95, 89.99, 'https://images.unsplash.com/photo-1609592806596-4e8d2de1c62b?w=800', 'active', 44.5, 95),
('electric-kettle-temp-control', 'Electric Kettle Temperature Control - 1.7L Glass with LED', 'Brew perfect tea and coffee with precise temperature control. Six preset temperatures.', 'Express Prime', 'Kitchen Appliances', ARRAY['trending', 'new', 'ai-pick'], 44.95, 79.99, 'https://images.unsplash.com/photo-1594226801341-41427b4e5c22?w=800', 'active', 43.8, 100),

-- Computer & Tech Accessories
('laptop-cooling-pad-6fans', 'Laptop Cooling Pad with 6 Fans - RGB LED Adjustable Height', 'Prevent overheating and extend laptop lifespan with powerful cooling technology.', 'Express Prime', 'Computer Accessories', ARRAY['smart-tech', 'trending', 'ai-pick'], 34.95, 59.99, 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800', 'active', 41.7, 90),
('usb-condenser-mic-boom', 'USB Condenser Microphone for Streaming - Cardioid with Boom Arm', 'Capture studio-quality audio for streaming, podcasting, and content creation.', 'Express Prime', 'Electronics', ARRAY['smart-tech', 'trending', 'new', 'ai-pick'], 69.95, 129.99, 'https://images.unsplash.com/photo-1598550476439-6847785fcea6?w=800', 'active', 46.2, 60),
('blue-light-glasses-2pack', 'Blue Light Blocking Glasses 2-Pack - Computer Glasses Eye Strain', 'Protect your eyes from digital eye strain and improve sleep quality.', 'Express Prime', 'Health & Wellness', ARRAY['trending', 'bestseller', 'ai-pick'], 24.95, 49.99, 'https://images.unsplash.com/photo-1574258495973-f010dfbb5371?w=800', 'active', 50.1, 170),
('wireless-keyboard-mouse-combo', 'Wireless Keyboard and Mouse Combo - Rechargeable Full-Size', 'Upgrade your workspace with this reliable wireless combo.', 'Express Prime', 'Computer Accessories', ARRAY['trending', 'bestseller', 'ai-pick'], 39.95, 69.99, 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800', 'active', 42.9, 110),
('essential-oil-diffuser-400ml', 'Essential Oil Diffuser 400ml - Ultrasonic Aromatherapy 7 LED Colors', 'Create a relaxing atmosphere with soothing aromatherapy and ambient lighting.', 'Express Prime', 'Home & Living', ARRAY['trending', 'bestseller', 'ai-pick'], 29.95, 54.99, 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=800', 'active', 45.6, 150),

-- Home & Living
('weighted-blanket-15lbs', 'Weighted Blanket 15lbs - Cooling Breathable for Adults', 'Improve sleep quality and reduce anxiety with gentle, even pressure.', 'Express Prime', 'Home & Living', ARRAY['trending', 'bestseller', 'ai-pick'], 79.95, 139.99, 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800', 'active', 42.9, 55),
('bike-phone-mount-universal', 'Bike Phone Mount - Universal Motorcycle Handlebar Holder', 'Navigate safely with your phone securely mounted on handlebars.', 'Express Prime', 'Sports & Outdoors', ARRAY['trending', 'bestseller', 'ai-pick'], 16.95, 29.99, 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800', 'active', 43.5, 180),
('acupressure-mat-pillow-set', 'Acupressure Mat and Pillow Set - Massage Mat for Back Pain', 'Relieve muscle tension and promote relaxation with ancient acupressure therapy.', 'Express Prime', 'Health & Wellness', ARRAY['trending', 'bestseller', 'ai-pick'], 34.95, 69.99, 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800', 'active', 50.1, 85),
('portable-monitor-156', 'Portable Monitor 15.6 Inch - USB-C HDMI Second Screen', 'Boost productivity with a second screen anywhere you work. Full HD 1080P IPS display.', 'Express Prime', 'Computer Accessories', ARRAY['smart-tech', 'trending', 'new', 'ai-pick'], 129.95, 199.99, 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800', 'active', 35.0, 40),
('hand-grip-strengthener-set', 'Hand Grip Strengthener Set - Adjustable Resistance Trainer', 'Build powerful grip strength for sports, music, and daily activities.', 'Express Prime', 'Fitness', ARRAY['trending', 'bestseller', 'ai-pick'], 24.95, 44.99, 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800', 'active', 44.6, 140),

-- Organization & Accessories
('cable-management-box-2pack', 'Cable Management Box Set of 2 - Cord Organizer Hides Power Strips', 'Eliminate unsightly cable clutter with these sleek organizer boxes.', 'Express Prime', 'Office Accessories', ARRAY['trending', 'bestseller', 'ai-pick'], 29.95, 49.99, 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800', 'active', 40.1, 120),
('silk-sleep-mask-3d', 'Silk Sleep Mask 3D Contoured - Eye Mask Complete Darkness', 'Experience deeper, more restful sleep with total light blocking.', 'Express Prime', 'Health & Wellness', ARRAY['trending', 'bestseller', 'ai-pick'], 19.95, 34.99, 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800', 'active', 43.0, 160),
('phone-ring-holder-360', 'Phone Ring Holder 360° - Magnetic Car Mount Compatible', 'Prevent drops and improve one-handed phone use with this versatile ring holder.', 'Express Prime', 'Phone Accessories', ARRAY['trending', 'ai-pick'], 12.95, 19.99, 'https://images.unsplash.com/photo-1609592806596-4e8d2de1c62b?w=800', 'active', 35.2, 250),
('drawer-organizer-bamboo', 'Drawer Organizer Dividers Adjustable Bamboo - Storage Bins', 'Maximize drawer space with customizable bamboo dividers.', 'Express Prime', 'Home Organization', ARRAY['trending', 'ai-pick'], 34.95, 59.99, 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800', 'active', 41.7, 100),
('laptop-sleeve-156-waterproof', 'Laptop Sleeve 15.6 Inch Waterproof - Protective Case', 'Safeguard your laptop with military-grade protection.', 'Express Prime', 'Computer Accessories', ARRAY['trending', 'ai-pick'], 24.95, 39.99, 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800', 'active', 37.6, 130),

-- More Fitness & Home
('yoga-mat-extra-thick', 'Yoga Mat Extra Thick - Non-Slip Exercise Mat 72x24', 'Practice yoga and exercise in comfort with premium cushioning.', 'Express Prime', 'Fitness', ARRAY['trending', 'bestseller', 'ai-pick'], 29.95, 54.99, 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800', 'active', 45.6, 110),
('usb-hub-7port-switches', 'USB Hub 3.0 7-Port - High-Speed Data Hub Individual Switches', 'Expand connectivity with seven high-speed USB 3.0 ports.', 'Express Prime', 'Computer Accessories', ARRAY['smart-tech', 'trending', 'ai-pick'], 24.95, 39.99, 'https://images.unsplash.com/photo-1625723044792-44de16c38299?w=800', 'active', 37.6, 150),
('digital-kitchen-scale-22lb', 'Digital Kitchen Scale - Food Scale LCD Display 22lb Capacity', 'Achieve perfect recipes with precise measurements.', 'Express Prime', 'Kitchen Gadgets', ARRAY['trending', 'bestseller', 'ai-pick'], 19.95, 34.99, 'https://images.unsplash.com/photo-1594228420014-1c91a5b5b1ce?w=800', 'active', 43.0, 140),
('shoe-rack-4tier-16pairs', 'Shoe Rack 4-Tier Stackable - Shoe Organizer Holds 16 Pairs', 'Declutter entryways and closets with efficient shoe storage.', 'Express Prime', 'Home Organization', ARRAY['trending', 'ai-pick'], 29.95, 49.99, 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800', 'active', 40.1, 80),
('handheld-garment-steamer', 'Handheld Garment Steamer Portable - 1200W Fast Heat', 'Remove wrinkles quickly without an ironing board. Powerful 1200W.', 'Express Prime', 'Home Appliances', ARRAY['trending', 'new', 'ai-pick'], 34.95, 59.99, 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800', 'active', 41.7, 90),

-- Final Products
('pill-organizer-7day-4times', 'Pill Organizer 7 Day - Weekly Medication Organizer 4 Times', 'Never miss a dose with this comprehensive pill organizer.', 'Express Prime', 'Health & Wellness', ARRAY['trending', 'bestseller', 'ai-pick'], 16.95, 29.99, 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800', 'active', 43.5, 180),
('reusable-grocery-bags-6pack', 'Reusable Grocery Bags Set of 6 - Heavy Duty Shopping Bags', 'Reduce plastic waste with durable, eco-friendly shopping bags.', 'Express Prime', 'Home & Living', ARRAY['trending', 'ai-pick'], 19.95, 34.99, 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800', 'active', 43.0, 200),
('toilet-night-light-motion', 'Toilet Night Light Motion Activated - LED Bathroom 16 Colors', 'Navigate safely to the bathroom at night without harsh overhead lights.', 'Express Prime', 'Home & Living', ARRAY['trending', 'new', 'ai-pick'], 14.95, 24.99, 'https://images.unsplash.com/photo-1565814329452-e1efa11c5b89?w=800', 'active', 40.2, 220),
('lint-roller-pet-hair', 'Lint Roller Extra Sticky - Pet Hair Remover with 5 Refills', 'Keep clothes and furniture free from pet hair, lint, and dust.', 'Express Prime', 'Home & Living', ARRAY['trending', 'bestseller', 'ai-pick'], 12.95, 19.99, 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=800', 'active', 35.2, 250),
('silicone-baking-mats-3pack', 'Silicone Baking Mats Set of 3 - Non-Stick Reusable Sheets', 'Eliminate parchment paper waste with reusable baking mats.', 'Express Prime', 'Kitchen Gadgets', ARRAY['trending', 'ai-pick'], 16.95, 29.99, 'https://images.unsplash.com/photo-1594228420014-1c91a5b5b1ce?w=800', 'active', 43.5, 160)
ON CONFLICT (handle) DO UPDATE SET
  title = EXCLUDED.title, description = EXCLUDED.description, vendor = EXCLUDED.vendor,
  product_type = EXCLUDED.product_type, tags = EXCLUDED.tags, price = EXCLUDED.price,
  compare_at_price = EXCLUDED.compare_at_price, image_url = EXCLUDED.image_url,
  status = EXCLUDED.status, margin_percent = EXCLUDED.margin_percent,
  inventory_quantity = EXCLUDED.inventory_quantity, updated_at = now();

-- Add performance metrics for new products
INSERT INTO performance_metrics (product_id, date, views, add_to_carts, orders_count, revenue, refund_count, refund_amount)
SELECT 
  p.id,
  CURRENT_DATE - (random() * 14)::int,
  (random() * 600 + 100)::int,
  (random() * 60 + 10)::int,
  (random() * 25 + 5)::int,
  (random() * 2500 + 200)::decimal(10,2),
  CASE WHEN random() > 0.8 THEN (random() * 2)::int ELSE 0 END,
  CASE WHEN random() > 0.8 THEN (random() * 80)::decimal(10,2) ELSE 0 END
FROM products p
WHERE p.vendor = 'Express Prime' AND p.status = 'active'
ON CONFLICT DO NOTHING;
